---
- hosts: all
  tasks:
    - name: Install pip
      become: true
      apt:
        name:
          - python-pip
          - python-setuptools

    - name: install pip deps
      pip:
        name: '{{ item.name }}'
        version: '{{ item.version }}'
      with_items:
        - name: docker
          version: 3.4.1
        - name: requests
          version: 2.21.0
        - name: docker-compose
          version: 1.24.0

    - name: Docker runtime deps
      apt:
        name: libltdl7

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present
