---
global:
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

#rule_files:
#  - rules/recording_rules.yml
#  - rules/alerting_rules.yml
