---
global:
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['172.19.0.1:9090']
  
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['172.19.0.1:9100']

#rule_files:
#  - rules/recording_rules.yml
#  - rules/alerting_rules.yml
