---
- name: Create grafana dir
  file:
    path: '{{ grafana_dir }}'
    state: directory
    mode: 0777
    owner: anton

- name: Create grafana data dir
  file:
    path: '{{ grafana_dir }}/data'
    state: directory
    mode: 0777
    owner: anton

- name: Create data sources dir
  file:
    path: '{{ grafana_dir }}/provisioning/datasources'
    state: directory
    mode: 0777
    owner: anton

- name: Create dashboards dir
  file:
    path: '{{ grafana_dir }}/provisioning/dashboards'
    state: directory
    mode: 0777

- name: Add Grafana config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0777
  with_items:
    - src: datasource.yml
      dest: '{{ grafana_dir }}/provisioning/datasources/datasources.yml'
    - src: dashboards.yml
      dest: '{{ grafana_dir }}/provisioning/dashboards/dashboards.yml'
    - src: docker-compose.yml
      dest: '{{ grafana_dir }}/docker-compose.yml'
    - src: dashboard.json
      dest: '{{ grafana_dir }}/provisioning/dashboards/dashboard.json'

- name: Pull image
  docker_image:
    name: '{{ grafana_image }}'
    force: true

- name: Start container
  docker_service:
    project_src: '{{ grafana_dir }}'