---
- name: Create grafana dirs
  file:
    path: '{{ item }}'
    state: directory
    mode: 0770
    group: docker
  with_items:
    - '{{ grafana_dir }}/data'
    - '{{ grafana_dir }}/provisioning/datasources'
    - '{{ grafana_dir }}/provisioning/dashboards'

- name: Add Grafana config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0660
    group: docker
  with_items:
    - src: datasource.yml
      dest: '{{ grafana_dir }}/provisioning/datasources/datasources.yml'
    - src: dashboards.yml
      dest: '{{ grafana_dir }}/provisioning/dashboards/dashboards.yml'
    - src: docker-compose.yml
      dest: '{{ grafana_dir }}/docker-compose.yml'
    - src: dashboard.json
      dest: '{{ grafana_dir }}/provisioning/dashboards/dashboard.json'

- name: Pull image
  docker_image:
    name: '{{ grafana_image }}'
    force: true

- name: Start container
  docker_service:
    project_src: '{{ grafana_dir }}'
