- name: Create dirs
  file:
    path: '{{ item }}'
    state: directory
    mode: 0770
    group: docker
  with_items:
    - '{{ alertmanager_dir }}'
    - '{{ alertmanager_dir }}/data'

- name: Template config file
  template:
    src: alertmanager.yml
    dest: '{{ alertmanager_dir }}/alertmanager.yml'
    mode: 0660
    group: docker

- name: Pull image
  docker_image:
    name: '{{ alertmanager_image }}'
    force: true

- name: Start container
  docker_container:
    image: '{{ alertmanager_image }}'
    name: '{{ alertmanager_container_name }}'
    networks:
      - name: monitoring
    restart_policy: unless-stopped
    ports:
      - '127.0.0.1:9093:9093'
    command:
      - '--config.file={{ alertmanager_dir }}/alertmanager.yml'
      - '--storage.path={{ alertmanager_dir }}/data'
    volumes:
      - '{{ alertmanager_dir }}:{{ alertmanager_dir }}'
    user: 1000
